### PR TITLE
Add sigar.so for PI2

### PR DESCRIPTION
**Pull request by creationix**

### CODE REVIEW

**Comment by rphillips** [comment]
+1

**Comment by pquerna** [comment]
isn't it weird to check in binary .so to git?

**Comment by creationix** [comment]
@pquerna that's the current best practice for binary libraries using lit.  I don't want to rely on people having a proper build toolchain setup just to use lit libraries.

**Comment by pquerna** [comment]
how does someone re-create these binary files?

**Comment by rphillips** [comment]
On the buildbots for agent2, luvi and sigar are built for each distribution because of the libc incompatibilities between the different distributions. I'll document this more.

[1] https://github.com/virgo-agent-toolkit/lua-sigar

**Comment by rphillips** [comment]
Added a README to the `libs/` folder:

https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/commit/7efaddabb2216b419ab1ae7544142971a4a5cc6e

**Pull request merged**
