### PR TITLE
Add new lshw hostinfo check

### PR DESCRIPTION
**Pull request by creationix**
https://jira.rax.io/secure/RapidBoard.jspa?rapidView=559&view=detail&selectedIssue=INT-1603

### CODE REVIEW

**Comment by creationix** [comment]
Tested this locally and on a real cloud server using raxmon client.

Everything is working as designed.

Here is sample output:

```json
root@server-02:/var/log# rackspace-monitoring-agent -e hostinfo_runner -x lshw
{"Debug":{"InfoType":"LSHW", "OS":"linux"}}

{
  "metrics":{
    "info":{
      "claimed":true,
      "version":"4.1.5",
      "handle":"DMI:0100",
      "children":[{
          "claimed":true,
          "physid":"0",
          "id":"core",
          "children":[{
              "claimed":true,
              "version":"4.1.5",
              "id":"firmware:0",
              "class":"memory",
              "capabilities":{
                "edd":"Enhanced Disk Drive extensions",
                "pci":"PCI bus"
              },
              "units":"bytes",
              "size":98304,
              "date":"11/28/2013",
              "physid":"0",
              "vendor":"Xen",
              "description":"BIOS"
            },{
              "claimed":true,
              "physid":"1",
              "handle":"DMI:0401",
              "capabilities":{
                "apic":"on-chip advanced programmable interrupt controller (APIC)",
                "pni":true,
                "nx":"no-execute bit (NX)",
                "pse":"page size extensions",
                "sse":"streaming SIMD extensions (SSE)",
                "fpu_exception":"FPU exceptions reporting",
                "sse2":"streaming SIMD extensions (SSE2)",
                "wp":true,
                "popcnt":true,
                "fsgsbase":true,
                "sep":"fast system calls",
                "mca":"machine check architecture",
                "cx16":true,
                "nopl":true,
                "cx8":"compare and exchange 8-byte",
                "clflush":true,
                "mtrr":"memory type range registers",
                "de":"debugging extensions",
                "x2apic":true,
                "fpu":"mathematical co-processor",
                "rep_good":true,
                "syscall":"fast system calls",
                "mmx":"multimedia extensions (MMX)",
                "vme":"virtual mode extensions",
                "erms":true,
                "pge":"page global enable",
                "smep":true,
                "tsc_deadline_timer":true,
                "hypervisor":true,
                "ssse3":true,
                "sse4_1":true,
                "lahf_lm":true,
                "aes":true,
                "tsc":"time stamp counter",
                "pclmulqdq":true,
                "f16c":true,
                "x86-64":"64bits extensions (x86-64)",
                "sse4_2":true,
                "rdrand":true,
                "mce":"machine check exceptions",
                "cmov":"conditional move instruction",
                "msr":"model-specific registers",
                "pae":"4GB+ memory addressing (Physical Address Extension)",
                "rdtscp":true,
                "pat":"page attribute table",
                "fxsr":"fast floating point save/restore",
                "constant_tsc":true
              },
              "vendor":"Intel Corp.",
              "slot":"CPU 1",
              "width":64,
              "capacity":2800000000,
              "size":2800000000,
              "units":"Hz",
              "product":"Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz",
              "businfo":"cpu@0",
              "id":"cpu:0",
              "class":"processor",
              "description":"CPU"
            },{
              "claimed":true,
              "physid":"2",
              "handle":"DMI:0402",
              "capabilities":{
                "apic":"on-chip advanced programmable interrupt controller (APIC)",
                "pni":true,
                "nx":"no-execute bit (NX)",
                "pse":"page size extensions",
                "sse":"streaming SIMD extensions (SSE)",
                "fpu_exception":"FPU exceptions reporting",
                "sse2":"streaming SIMD extensions (SSE2)",
                "wp":true,
                "popcnt":true,
                "fsgsbase":true,
                "sep":"fast system calls",
                "mca":"machine check architecture",
                "cx16":true,
                "nopl":true,
                "cx8":"compare and exchange 8-byte",
                "clflush":true,
                "mtrr":"memory type range registers",
                "de":"debugging extensions",
                "x2apic":true,
                "fpu":"mathematical co-processor",
                "rep_good":true,
                "syscall":"fast system calls",
                "mmx":"multimedia extensions (MMX)",
                "vme":"virtual mode extensions",
                "erms":true,
                "pge":"page global enable",
                "smep":true,
                "tsc_deadline_timer":true,
                "hypervisor":true,
                "ssse3":true,
                "sse4_1":true,
                "lahf_lm":true,
                "aes":true,
                "tsc":"time stamp counter",
                "pclmulqdq":true,
                "f16c":true,
                "x86-64":"64bits extensions (x86-64)",
                "sse4_2":true,
                "rdrand":true,
                "mce":"machine check exceptions",
                "cmov":"conditional move instruction",
                "msr":"model-specific registers",
                "pae":"4GB+ memory addressing (Physical Address Extension)",
                "rdtscp":true,
                "pat":"page attribute table",
                "fxsr":"fast floating point save/restore",
                "constant_tsc":true
              },
              "vendor":"Intel Corp.",
              "slot":"CPU 2",
              "width":64,
              "capacity":2800000000,
              "size":2800000000,
              "units":"Hz",
              "product":"Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz",
              "businfo":"cpu@1",
              "id":"cpu:1",
              "class":"processor",
              "description":"CPU"
            },{
              "claimed":true,
              "physid":"3",
              "handle":"DMI:1000",
              "children":[{
                  "claimed":true,
                  "physid":"0",
                  "handle":"DMI:1100",
                  "class":"memory",
                  "slot":"DIMM 0",
                  "units":"bytes",
                  "width":64,
                  "size":4022337536,
                  "id":"bank:0",
                  "description":"DIMM RAM"
                },{
                  "claimed":true,
                  "physid":"1",
                  "handle":"DMI:1100",
                  "class":"memory",
                  "slot":"DIMM 0",
                  "units":"bytes",
                  "width":64,
                  "size":4022337536,
                  "id":"bank:1",
                  "description":"DIMM RAM"
                }],
              "capacity":4022337536,
              "units":"bytes",
              "class":"memory",
              "id":"memory:0",
              "description":"System Memory"
            },{
              "claimed":true,
              "version":"4.1.5",
              "id":"firmware:1",
              "class":"memory",
              "capabilities":{
                "edd":"Enhanced Disk Drive extensions",
                "pci":"PCI bus"
              },
              "units":"bytes",
              "size":98304,
              "date":"11/28/2013",
              "physid":"4",
              "vendor":"Xen",
              "description":"BIOS"
            },{
              "claimed":true,
              "physid":"5",
              "handle":"DMI:0401",
              "vendor":"Intel",
              "slot":"CPU 1",
              "capacity":2800000000,
              "units":"Hz",
              "size":2800000000,
              "businfo":"cpu@2",
              "class":"processor",
              "id":"cpu:2",
              "description":"CPU"
            },{
              "claimed":true,
              "physid":"6",
              "handle":"DMI:0402",
              "vendor":"Intel",
              "slot":"CPU 2",
              "capacity":2800000000,
              "units":"Hz",
              "size":2800000000,
              "businfo":"cpu@3",
              "class":"processor",
              "id":"cpu:3",
              "description":"CPU"
            },{
              "capacity":4022337536,
              "claimed":true,
              "physid":"7",
              "handle":"DMI:1000",
              "units":"bytes",
              "class":"memory",
              "id":"memory:1",
              "description":"System Memory"
            },{
              "class":"memory",
              "physid":"8",
              "id":"memory:2"
            },{
              "class":"memory",
              "physid":"9",
              "id":"memory:3"
            },{
              "claimed":true,
              "physid":"100",
              "handle":"PCIBUS:0000:00",
              "children":[{
                  "claimed":true,
                  "physid":"1",
                  "handle":"PCI:0000:00:01.0",
                  "vendor":"Intel Corporation",
                  "capabilities":{
                    "bus_master":"bus mastering",
                    "isa":true
                  },
                  "configuration":{
                    "latency":"0"
                  },
                  "class":"bridge",
                  "width":32,
                  "version":"00",
                  "product":"82371SB PIIX3 ISA [Natoma/Triton II]",
                  "businfo":"pci@0000:00:01.0",
                  "id":"isa",
                  "clock":33000000,
                  "description":"ISA bridge"
                },{
                  "claimed":true,
                  "physid":"1.1",
                  "handle":"PCI:0000:00:01.1",
                  "vendor":"Intel Corporation",
                  "capabilities":{
                    "bus_master":"bus mastering",
                    "ide":true
                  },
                  "configuration":{
                    "driver":"ata_piix",
                    "latency":"64"
                  },
                  "class":"storage",
                  "width":32,
                  "version":"00",
                  "product":"82371SB PIIX3 IDE [Natoma/Triton II]",
                  "businfo":"pci@0000:00:01.1",
                  "id":"ide",
                  "clock":33000000,
                  "description":"IDE interface"
                },{
                  "claimed":true,
                  "physid":"1.2",
                  "handle":"PCI:0000:00:01.2",
                  "vendor":"Intel Corporation",
                  "capabilities":{
                    "bus_master":"bus mastering",
                    "uhci":"Universal Host Controller Interface (USB1)"
                  },
                  "configuration":{
                    "driver":"uhci_hcd",
                    "latency":"64"
                  },
                  "class":"bus",
                  "width":32,
                  "version":"01",
                  "product":"82371SB PIIX3 USB [Natoma/Triton II]",
                  "businfo":"pci@0000:00:01.2",
                  "id":"usb",
                  "clock":33000000,
                  "description":"USB controller"
                },{
                  "width":32,
                  "physid":"1.3",
                  "handle":"PCI:0000:00:01.3",
                  "product":"82371AB/EB/MB PIIX4 ACPI",
                  "capabilities":{
                    "bridge":true,
                    "bus_master":"bus mastering"
                  },
                  "configuration":{
                    "latency":"0"
                  },
                  "class":"bridge",
                  "version":"01",
                  "vendor":"Intel Corporation",
                  "businfo":"pci@0000:00:01.3",
                  "id":"bridge",
                  "clock":33000000,
                  "description":"Bridge"
                },{
                  "claimed":true,
                  "physid":"2",
                  "handle":"PCI:0000:00:02.0",
                  "vendor":"Cirrus Logic",
                  "capabilities":{
                    "bus_master":"bus mastering",
                    "rom":"extension ROM",
                    "vga_controller":true
                  },
                  "configuration":{
                    "driver":"cirrus",
                    "latency":"0"
                  },
                  "class":"display",
                  "width":32,
                  "version":"00",
                  "product":"GD 5446",
                  "businfo":"pci@0000:00:02.0",
                  "id":"display",
                  "clock":33000000,
                  "description":"VGA compatible controller"
                },{
                  "claimed":true,
                  "physid":"3",
                  "handle":"PCI:0000:00:03.0",
                  "vendor":"XenSource, Inc.",
                  "capabilities":{
                    "scsi":true,
                    "bus_master":"bus mastering"
                  },
                  "configuration":{
                    "driver":"xen-platform-pci",
                    "latency":"0"
                  },
                  "class":"storage",
                  "width":32,
                  "version":"01",
                  "product":"Xen Platform Device",
                  "businfo":"pci@0000:00:03.0",
                  "id":"scsi",
                  "clock":33000000,
                  "description":"SCSI storage controller"
                }],
              "vendor":"Intel Corporation",
              "class":"bridge",
              "width":32,
              "version":"02",
              "product":"440FX - 82441FX PMC [Natoma]",
              "businfo":"pci@0000:00:00.0",
              "id":"pci",
              "clock":33000000,
              "description":"Host bridge"
            }],
          "class":"bus",
          "description":"Motherboard"
        },{
          "claimed":true,
          "physid":"1",
          "id":"network:0",
          "class":"network",
          "logicalname":"eth0",
          "serial":"bc:76:4e:04:e9:b7",
          "capabilities":{
            "ethernet":true,
            "physical":"Physical interface"
          },
          "description":"Ethernet interface",
          "configuration":{
            "broadcast":"yes",
            "link":"yes",
            "driver":"vif",
            "multicast":"yes",
            "ip":"172.99.115.246"
          }
        },{
          "claimed":true,
          "physid":"2",
          "id":"network:1",
          "class":"network",
          "logicalname":"eth1",
          "serial":"bc:76:4e:04:e9:da",
          "capabilities":{
            "ethernet":true,
            "physical":"Physical interface"
          },
          "description":"Ethernet interface",
          "configuration":{
            "broadcast":"yes",
            "link":"yes",
            "driver":"vif",
            "multicast":"yes",
            "ip":"10.210.65.32"
          }
        }],
      "vendor":"Xen",
      "capabilities":{
        "smbios-2.4":"SMBIOS version 2.4",
        "dmi-2.4":"DMI version 2.4",
        "vsyscall32":"32-bit processes"
      },
      "configuration":{
        "boot":"normal",
        "uuid":"F156B37D-C4E9-CA91-683A-9DECEA8B780E"
      },
      "width":64,
      "serial":"f156b37d-c4e9-ca91-683a-9decea8b780e",
      "product":"HVM domU ()",
      "id":"server-02",
      "class":"system",
      "description":"Computer"
    }
  },
  "timestamp":1485374049000
}
```

**Comment by creationix** [comment]
Weird that lint fails here, but passes locally.  Git must be doing something funny with newlines and whitespace?

**Comment by rphillips** [comment]
We need to add the following code to this host info:

```lua
function Info:getPlatforms()
  return {'linux'}
end
```

**Comment by creationix** [comment]
Anything else this needs?  The CI is still failing.  Is that unrelated?

**Comment by wolfdancer** [comment]
@rphillips @creationix how are we on merging this PR? It has been stuck for a while.

**Comment by rphillips** [comment]
it's failing on an unclosed pipe: https://travis-ci.org/virgo-agent-toolkit/rackspace-monitoring-agent/builds/196765966#L1865

**Comment by creationix** [comment]
Ok, fixed the travis issues!

The appveyor issues look to be unrelated and have been broken for about 5 months.

**Comment by rjemanuele** [comment]
I'm +1 on this.

**Comment by rphillips** [comment]
+1

**Pull request merged**
