### PR TITLE
create the plugin directory for RPM and DEBs

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by creationix** [comment]
+1

This will cover most agent installs right?

**Comment by rphillips** [comment]
yes. this will cover all the install base but windows.

**Comment by rjemanuele** [comment]
the windows installer already has the plugin directory https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/blob/master/cmake/package/windows/virgo.wxs#L54

**Comment by rphillips** [comment]
awesome. thanks rob

**Pull request merged**
